---
- name: Database
  version: v1alpha1
  group: app.example.com
  kind: Database
  path: /opt/ansible/playbook.yaml
- name: Example
  version: v1alpha1
  group: app.example.com
  kind: Frontend
  path: /opt/ansible/playbook.yaml
